nodeLinker: node-modules

npmRegistries:
  "https://npm.remix.run":
    npmAuthToken: 58bd1f71ce1f77157c01245533593477ae0dd030

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-1.23.0-20210103.1434.cjs
