// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Hello(props) {
  return React.createElement("div", undefined, "Hello " + props.person + "!");
}

var make = Hello;

export {
  make ,
}
/* react Not a pure module */
