'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NextThemes from "next-themes";
import * as Utils from "../lib/utils";

function cn(prim) {
  return Utils.cn(prim);
}

function ModeToggle(props) {
  var match = NextThemes.useTheme();
  var setTheme = match.setTheme;
  var resolvedTheme = match.resolvedTheme;
  return React.createElement("button", {
              className: props.className,
              type: "button",
              onClick: (function (param) {
                  setTheme(resolvedTheme === "light" ? "dark" : "light");
                })
            }, React.createElement("span", {
                  className: "sr-only"
                }, "Toggle theme"), React.createElement("span", {
                  className: "dark:inline hidden"
                }, "☽"), React.createElement("span", {
                  className: "inline dark:hidden"
                }, "☼"));
}

var make = ModeToggle;

export {
  cn ,
  make ,
}
/* react Not a pure module */
