// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function NotFound(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "404..."), React.createElement("h2", {
                  style: {
                    fontSize: "6rem",
                    margin: "0"
                  }
                }, "🏜"), React.createElement("p", undefined, "여긴 아무것도 없답니다..."));
}

var make = NotFound;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
