import TheGreatBackButton from "~/components/TheGreatBackButton";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <main
          className="
              min-h-screen
              flex
              flex-col
              px-[1.8em]
              pb-[4em]
              text-slate-800
              bg-slate-50
              dark:bg-gray-800
              dark:text-slate-100
              leading-loose
              whitespace-pre-wrap
              break-words
              font-serif
              "
        >
          <div className="h-8" />
          <TheGreatBackButton />
          {children}
        </main>
      </body>
    </html>
  );
}
