// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Gatsby from "gatsby";

function str(prim) {
  return prim;
}

function Bio(Props) {
  var social = Props.social;
  return React.createElement(React.Fragment, undefined, React.createElement(Gatsby.Link, {
                  children: "about",
                  to: "/about"
                }), "  |  ", React.createElement("a", {
                  href: "https://github.com/" + social.github
                }, "github"));
}

var Link;

var make = Bio;

export {
  Link ,
  str ,
  make ,
  
}
/* react Not a pure module */
