// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Bio(Props) {
  var social = Props.social;
  return React.createElement(React.Fragment, undefined, React.createElement("a", {
                  href: "/about"
                }, "about"), "  |  ", React.createElement("a", {
                  href: "https://github.com/" + social.github
                }, "github"));
}

var make = Bio;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
