// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var currentYear = new Date().getFullYear().toFixed();

function Footer(Props) {
  var children = Props.children;
  return React.createElement("footer", {
              style: {
                color: "var(--tex-secondary-color)",
                display: "flex",
                marginTop: "20px",
                padding: "20px 0",
                flexDirection: "row",
                justifyContent: "space-between"
              }
            }, React.createElement("p", undefined, "© " + currentYear + " Sehyun Chung"), React.createElement("p", undefined, children));
}

var make = Footer;

var $$default = Footer;

export {
  currentYear ,
  make ,
  $$default ,
  $$default as default,
  
}
/* currentYear Not a pure module */
