// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function append(child, parent) {
  if (parent !== undefined) {
    Caml_option.valFromOption(parent).appendChild(child);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function Utterances(Props) {
  var utterancesRef = React.useRef(null);
  React.useEffect((function () {
          var utterances = document.createElement("script");
          List.iter((function (param) {
                  utterances.setAttribute(param[0], param[1]);
                  return /* () */0;
                }), /* :: */[
                /* tuple */[
                  "src",
                  "https://utteranc.es/client.js"
                ],
                /* :: */[
                  /* tuple */[
                    "repo",
                    "sehyunchung/sehyunchung.github.io"
                  ],
                  /* :: */[
                    /* tuple */[
                      "issue-term",
                      "pathname"
                    ],
                    /* :: */[
                      /* tuple */[
                        "theme",
                        "photon-dark"
                      ],
                      /* :: */[
                        /* tuple */[
                          "crossorigin",
                          "anonymous"
                        ],
                        /* :: */[
                          /* tuple */[
                            "async",
                            "true"
                          ],
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]);
          append(utterances, Caml_option.nullable_to_opt(utterancesRef.current));
          return (function (param) {
                    return /* () */0;
                  });
        }));
  return React.createElement("div", {
              ref: utterancesRef,
              className: "utterances",
              style: {
                margin: "20px 0",
                maxWidth: "100%"
              }
            });
}

var make = Utterances;

export {
  append ,
  make ,
  
}
/* react Not a pure module */
